### ISSUE TITLE
Allow only one snap session.

### ISSUE THREAD

**Issue by wolfhammer** [jlyonsmith/easy#2]
Is it be possible to configure my project to only allow one snap session?  The "snap start -a" would then error out with something like "snap session already running".

**Comment by jlyonsmith** [comment]
@wolfhammer If you design it, it will ship. 😆 It's a good idea.  I've hit this problem myself many times. 
 Any suggestions on how this might work?  It can't just be a global flag, because what if you want to run `snap start` on another project?
